# Generated by Django 3.2.7 on 2021-10-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashnds',
            name='date_selected',
            field=models.DateField(max_length=255),
        ),
    ]
