# Generated by Django 3.2.7 on 2021-10-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_cashnds_date_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverWallets',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=255)),
                ('trans_amount', models.CharField(max_length=255)),
                ('trans_mode', models.CharField(max_length=255)),
                ('trans_type', models.CharField(max_length=255)),
                ('trans_reference', models.ImageField(upload_to='images/')),
                ('trans_status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'driver_wallets',
                'managed': False,
            },
        ),
    ]
