# Generated by Django 3.2.7 on 2021-11-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_driverwallets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverwallets',
            options={'managed': True},
        ),
    ]
