# Generated by Django 3.2.7 on 2021-11-05 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_driverwallets_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverwallets',
            name='trans_reference',
            field=models.CharField(max_length=255),
        ),
    ]
